"""Static slash command metadata."""

from __future__ import annotations

from .base import CommandDef

COMMAND_REGISTRY: tuple[CommandDef, ...] = (
    CommandDef("help", "Show available commands", "Info", aliases=("?",)),
    CommandDef("commands", "Browse all commands and categories", "Info"),
    CommandDef("status", "Show current session, provider, model, and state paths", "Session"),
    CommandDef("new", "Start a fresh session", "Session", aliases=("reset",)),
    CommandDef("clear", "Clear screen and start a fresh session", "Session", cli_only=True),
    CommandDef("history", "Show current conversation history", "Session", cli_only=True),
    CommandDef("retry", "Retry the last user message", "Session"),
    CommandDef("undo", "Remove the last user/assistant exchange", "Session"),
    CommandDef("compact", "Compress conversation context", "Session", args_hint="[focus]"),
    CommandDef("resume", "Resume a stored session", "Session", args_hint="[session-id|latest]"),
    CommandDef(
        "model",
        "Switch model or provider",
        "Configuration",
        args_hint="[model] [--provider id]",
    ),
    CommandDef("providers", "List configured and available providers", "Configuration"),
    CommandDef(
        "login",
        "Authenticate with a provider",
        "Configuration",
        args_hint="[provider=openai-codex]",
        subcommands=("openai-codex",),
    ),
    CommandDef(
        "logout",
        "Clear provider authentication",
        "Configuration",
        args_hint="[provider]",
        subcommands=("openai-codex",),
    ),
    CommandDef("config", "Show effective configuration", "Configuration"),
    CommandDef("env", "Show environment variables used by the runtime", "Configuration"),
    CommandDef(
        "tools",
        "List, enable, or disable tools",
        "Tools",
        args_hint="[list|enable|disable]",
    ),
    CommandDef(
        "skills",
        "Search, inspect, install, or reload skills",
        "Tools",
        args_hint="[search|inspect|install|reload]",
    ),
    CommandDef("mcp", "List MCP server configuration", "Extensions", args_hint="[list]"),
    CommandDef("plugin", "List local plugins", "Extensions", args_hint="[list]"),
    CommandDef("agents", "List custom agent definitions", "Extensions", args_hint="[list]"),
    CommandDef("hooks", "List local hook definitions", "Extensions", args_hint="[list]"),
    CommandDef("integrations", "List external integration status", "Integrations", args_hint="[name]"),
    CommandDef("ide", "Show IDE integration status", "Integrations", args_hint="[status]"),
    CommandDef("desktop", "Show desktop app integration status", "Integrations", args_hint="[status]"),
    CommandDef("chrome", "Show Chrome bridge integration status", "Integrations", args_hint="[status]"),
    CommandDef("voice", "Show voice input integration status", "Integrations", args_hint="[status]"),
    CommandDef("remote", "Show remote session integration status", "Integrations", args_hint="[status]"),
    CommandDef("mobile", "Show mobile handoff integration status", "Integrations", args_hint="[status]"),
    CommandDef("teleport", "Show teleport integration status", "Integrations", args_hint="[status]"),
    CommandDef("memory", "Inspect or edit layered memory", "Tools", args_hint="[show|search|edit]"),
    CommandDef("doctor", "Run local diagnostics", "Info"),
    CommandDef("usage", "Show token and cost usage", "Info"),
    CommandDef("version", "Show GenericAgent Engineered version", "Info"),
    CommandDef("stats", "Show session statistics as JSON", "Info"),
    CommandDef("summary", "Summarize the current conversation state", "Session"),
    CommandDef("export", "Export conversation history as JSON", "Session", args_hint="[json]"),
    CommandDef("diff", "Diff the last two conversation messages", "Session"),
    CommandDef("rename", "Rename the current session", "Session", args_hint="<name>"),
    CommandDef("sessions", "List sessions for the current agent home", "Session"),
    CommandDef("tasks", "Show current background tasks", "Session"),
    CommandDef("worktree", "Show git worktree status", "Session"),
    CommandDef("add-dir", "Add an extra working directory (not wired yet)", "Feature-gated"),
    CommandDef("advisor", "Start advisor prompt workflow (not wired yet)", "Feature-gated"),
    CommandDef("assistant", "Open assistant mode controls (not wired yet)", "Feature-gated"),
    CommandDef("branch", "Create a session branch (not wired yet)", "Feature-gated"),
    CommandDef("bridge", "Show browser bridge command help", "Integrations"),
    CommandDef("btw", "Create a free-code BTW note (not wired yet)", "Feature-gated"),
    CommandDef("color", "Switch terminal color mode (not wired yet)", "Feature-gated"),
    CommandDef("context", "Inspect context composition (not wired yet)", "Feature-gated"),
    CommandDef("cost", "Show exact provider cost (not wired yet)", "Feature-gated"),
    CommandDef("extra-usage", "Show extra usage quota (not wired yet)", "Feature-gated"),
    CommandDef("fast", "Toggle fast mode (not wired yet)", "Feature-gated"),
    CommandDef("feedback", "Send product feedback (not wired yet)", "Feature-gated"),
    CommandDef("files", "Open file picker/status surface (not wired yet)", "Feature-gated"),
    CommandDef("heapdump", "Write a TUI heap dump (not wired yet)", "Feature-gated"),
    CommandDef("insights", "Generate a usage insight report (not wired yet)", "Feature-gated"),
    CommandDef("init", "Initialize project instructions (not wired yet)", "Feature-gated"),
    CommandDef(
        "install-github-app",
        "Install the GitHub app workflow (not wired yet)",
        "Feature-gated",
    ),
    CommandDef(
        "install-slack-app",
        "Install the Slack app workflow (not wired yet)",
        "Feature-gated",
    ),
    CommandDef("onboarding", "Replay onboarding (not wired yet)", "Feature-gated"),
    CommandDef("passes", "Show free-code pass controls (not wired yet)", "Feature-gated"),
    CommandDef("plan", "Open plan mode controls (not wired yet)", "Feature-gated"),
    CommandDef("pr_comments", "Fetch PR comments (not wired yet)", "Feature-gated"),
    CommandDef("privacy-settings", "Open privacy settings (not wired yet)", "Feature-gated"),
    CommandDef("release-notes", "Show release notes (not wired yet)", "Feature-gated"),
    CommandDef("reload-plugins", "Reload plugin commands (not wired yet)", "Feature-gated"),
    CommandDef("remote-env", "Configure remote environment (not wired yet)", "Feature-gated"),
    CommandDef("remote-setup", "Run remote setup (not wired yet)", "Feature-gated"),
    CommandDef("reset-limits", "Reset mocked rate limits (not wired yet)", "Feature-gated"),
    CommandDef("review", "Start code review prompt workflow (not wired yet)", "Feature-gated"),
    CommandDef("rewind", "Rewind to an earlier message (not wired yet)", "Feature-gated"),
    CommandDef("copy", "Copy the latest output (not wired yet)", "Feature-gated"),
    CommandDef("security-review", "Start security review workflow (not wired yet)", "Feature-gated"),
    CommandDef("session", "Open session manager (not wired yet)", "Feature-gated"),
    CommandDef("share", "Share/export hosted transcript (not wired yet)", "Feature-gated"),
    CommandDef("stickers", "Open sticker picker (not wired yet)", "Feature-gated"),
    CommandDef("tag", "Tag the current session (not wired yet)", "Feature-gated"),
    CommandDef("terminal-setup", "Install shell integration (not wired yet)", "Feature-gated"),
    CommandDef("thinkback", "Open thinkback replay (not wired yet)", "Feature-gated"),
    CommandDef("thinkback-play", "Play thinkback trace (not wired yet)", "Feature-gated"),
    CommandDef("ultrareview", "Start ultrareview prompt workflow (not wired yet)", "Feature-gated"),
    CommandDef("upgrade", "Check for TUI upgrades (not wired yet)", "Feature-gated"),
    CommandDef("theme", "Open theme controls (TUI: Ctrl-T)", "Configuration"),
    CommandDef("vim", "Show Vim mode configuration", "Configuration"),
    CommandDef("keybindings", "Show TUI keyboard shortcuts", "Info"),
    CommandDef("statusline", "Show statusline configuration", "Configuration"),
    CommandDef("rate-limit-options", "Show rate-limit recovery options", "Info"),
    CommandDef("output-style", "Switch output style (not wired yet)", "Feature-gated"),
    CommandDef("effort", "Switch reasoning effort (not wired yet)", "Feature-gated"),
    CommandDef(
        "permissions",
        "List or change persistent tool approvals",
        "Permissions",
        args_hint="[list|allow|revoke|clear]",
    ),
    CommandDef(
        "sandbox-toggle",
        "Toggle approval-required vs yolo execution mode",
        "Permissions",
        args_hint="[status|on|off]",
    ),
    CommandDef("exit", "Exit the CLI", "Exit", aliases=("quit",), cli_only=True),
)
